# Generated by Django 3.0.6 on 2023-07-05 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_management', '0002_auto_20230705_1103'),
        ('cart', '0006_auto_20200529_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupon_management.Coupon'),
        ),
    ]
